language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_script:
- mongod --version
deploy:
    provider: heroku
    app: afternoon-ridge-54801
    api_key:
        secure: ETJK9okbFiZJhkufrzR+07JXP+KZ5lUipweTYjfJ6ELtN9wtY6EVB+/duJjEq9osVjNzA+F7dgEr2xTW6CrGQGDAdj4M6xRVvbbrj8h/3Uvyc0wn/Uiep59ATrKLpQze0KaXgDdD+u4gm0UliSitKm2u07+f6QGYs5PG1aeHHrN7NcSz69WuZd6JttXmcznkiCY5kKj0dRdMbosW50qR6goL7/ZVZULRma0jAwMK971NpZgcHb6q+V14wTpAeWq16B1Uzxxy8lxyvjXKmu/NuZ4Sf9CBhY+fctH7ssOo7g4uMQAIRyePGUNhHvh1u79yEUFHi4WFa+TagOb3uY61Ki/19B0X5qnK0Ve6c2PZUKqtvrNvRCJyEpkqRfwvfFTDeY0KOOrg58mZ2iVP3kHS7qAyV2vE+00yBsGzHL2y/jfGmjEn3eSWQTdCjMrC4pMQp+jz6dKkbfm+plZVIRQegQgkXWmaCqnDfVAoEVPuTgT2iDWUdLQDKloXqI1fgRsyURV/3PY4nRG9OIlMWUk1P5Ea2zNlQmQZJIgupNZ/Ja29Ih/y0+0uLivoJEiWHPeKL5UzsYuxvJSkNe6m37fE0ZauqopAzIEaqEJhrCWH5m2H/ZfOG22i3iXynZ0cwBqRcY8SLCjABLPER937lVzwN/ylqj4SCXy6sEOtGSzCQv8=
